# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleMovieList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleMovieList

  target 'SampleMovieListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SampleMovieListUITests' do
    # Pods for testing
  end

end
